# Import Packages

In [1]:
# we will import everything here
import numpy as np
import pygame
import random
from pygame.locals import *

from src.read_file import *
from src.parser import *

%reload_ext autoreload 
%autoreload 2 

# Modeling Environment Setup

In [2]:
# read the initial state of the cellular automata from a file
X = read_file("input.txt")
print("Input state matrix: ")
print(X)

# parse the input and get the required parameters
rows, cols, pedestrians, obstacles, targets = parser(X)

print("number of rows and columns")
print(rows, cols)

print("coordinate list of the pedestrians")
print(pedestrians)

print("coordinate list of the obstacles")
print(obstacles)

print("coordinate list of the targets")
print(targets)

Input state matrix: 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 2 3 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
number of rows and columns
5 5
coordinate list of the pedestrians
[[2 1]]
coordinate list of the obstacles
[[2 2]]
coordinate list of the targets
[[2 3]]


# Simulation 

In [4]:


black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)
orange=(250,89,8)
purple=(210,8,250)



#parse input
rows=20
columns=20
pedestrians= [[1,2],[2,3]]
obstacles= [[5,6],[7,8]]
targets= [[3,4],[2,5]]
WIDTH = 25
HEIGHT = 25
MARGIN = 5
grid = []
for row in range(rows):
    grid.append([])
    for column in range(columns):
        grid[row].append(0) 
grid[1][5] = 1
pygame.init()
font = pygame.font.SysFont('Calibri',20, False, False)
pds = font.render("P",True,black)
obs = font.render("O",True,black)
tgt = font.render("T",True,black)

window_size = [columns*WIDTH+(columns+1)*MARGIN,rows*HEIGHT + (rows+1)*MARGIN]
scr = pygame.display.set_mode(window_size)
pygame.display.set_caption("Grid")
done = False
clock = pygame.time.Clock()

while not done:
    for event in pygame.event.get(): 
        if event.type == pygame.QUIT: 
            done = True 
        
      #  elif event.type == pygame.MOUSEBUTTONDOWN:
       #     pos = pygame.mouse.get_pos()
        #    column = pos[0] // (WIDTH + MARGIN)
        #    row = pos[1] // (HEIGHT + MARGIN)
         #   grid[row][column] = 1
         #   print("Click ", pos, "Grid coordinates: ", row, column)
    scr.fill(black)
    for pedestrian in pedestrians:
        grid[pedestrian[0]][pedestrian[1]]=1
       
    for obstacle in obstacles:
        grid[obstacle[0]][obstacle[1]]=2
    for target in targets:
        grid[target[0]][target[1]]=3


    for row in range(rows):
        for column in range(columns):
            color = white
         
            if grid[row][column] == 1:
                color = red

            if grid[row][column] == 2:
                color = purple
            if grid[row][column] == 3:
                color = orange
            pygame.draw.rect(scr,
                             color,
                             [(MARGIN + WIDTH) * column + MARGIN,
                              (MARGIN + HEIGHT) * row + MARGIN,
                              WIDTH,
                              HEIGHT])
            if color ==red:
                 scr.blit(pds,[(MARGIN + WIDTH) * column + MARGIN,(MARGIN + HEIGHT) * row + MARGIN])
            if color ==purple:
                 scr.blit(obs,[(MARGIN + WIDTH) * column + MARGIN,(MARGIN + HEIGHT) * row + MARGIN])
            if color ==orange:
                 scr.blit(tgt,[(MARGIN + WIDTH) * column + MARGIN,(MARGIN + HEIGHT) * row + MARGIN])

          
    clock.tick(50)
    pygame.display.flip()
pygame.quit()

NameError: name 'pygame' is not defined